In [1]:
#import basic libaries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')



In [2]:
#load dataset creditcard.csv
df=pd.read_csv("creditcard.csv") 
#view first 5column
pd.set_option("display.max_columns",None) #to display all column
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

   Amount  Class  
0  149.62      0  
1    2.69      0  
2  378.66      0  
3  123.50      0  
4   69.99      0

In [3]:
#separate Independent variable(input variable) X and dependent variable 
#Y(target/output)
X=df.drop("Class",axis=1) #to store all inputs hold in X variable apart from
#deposit
Y=df["Class"]

In [4]:
#Split our dataset in train test of 70% & 30%
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.3,random_state=1)

In [5]:
from imblearn.over_sampling import RandomOverSampler
from sklearn.svm import SVC
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.preprocessing import StandardScaler

In [6]:
Y_train.value_counts()

0    199007
1       357
Name: Class, dtype: int64

In [7]:
ros=RandomOverSampler()

In [8]:
X_train_sample,Y_train_sample=ros.fit_resample(X_train,Y_train)
X_test_sample,Y_test_sample=ros.fit_resample(X_test,Y_test)

In [9]:
pd.Series(Y_train_sample).value_counts()

1    199007
0    199007
Name: Class, dtype: int64

In [10]:
pd.Series(Y_test).value_counts()

0    85308
1      135
Name: Class, dtype: int64

In [11]:
pd.Series(Y_test_sample).value_counts()

1    85308
0    85308
Name: Class, dtype: int64

In [12]:
#create object of StandardScaler
ss=StandardScaler()

In [13]:
X_train_sample=ss.fit_transform(X_train_sample)
X_test_sample=ss.fit_transform(X_test_sample)


In [14]:
X_train_sample

array([[ 0.87200176,  0.41154632, -0.44308984, ..., -0.08217341,
        -0.04191753, -0.36171427],
       [ 0.26282158,  0.44500601, -0.22507016, ..., -0.16325965,
        -0.00768469, -0.3841873 ],
       [ 1.51391003,  0.80927748, -0.47736343, ..., -0.13800754,
        -0.19182145, -0.41356545],
       ...,
       [-0.58177153, -0.89975173, -2.31032792, ...,  0.70925765,
        -2.40583502, -0.34242178],
       [-1.26681   , -2.81250917,  2.51730578, ...,  1.47737002,
         0.96664347, -0.00340125],
       [ 1.38333122, -0.47050268,  0.32708204, ..., -1.72988793,
        -0.27082568,  0.61542317]])

In [15]:
X_train1=X_train_sample[:99503]
Y_train1=Y_train_sample[:99503]
X_test1=X_test_sample[:42654]
Y_test1=Y_test_sample[:42654]

In [17]:
svc_poly=SVC(random_state=1,kernel="poly")

In [18]:
def create_model1(model):
    model.fit(X_train1,Y_train1)
    Y_pred=model.predict(X_test1)
    print(classification_report(Y_test1,Y_pred))
    print("confusion_matrix")
    print(confusion_matrix(Y_test1,Y_pred))
    return model

In [19]:
create_model1(svc_poly)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     42585
           1       0.80      0.51      0.62        69

    accuracy                           1.00     42654
   macro avg       0.90      0.75      0.81     42654
weighted avg       1.00      1.00      1.00     42654

confusion_matrix
[[42576     9]
 [   34    35]]


SVC(kernel='poly', random_state=1)

In [20]:
radial_svc=SVC(random_state=1,kernel="rbf")

In [21]:
create_model1(radial_svc)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     42585
           1       0.85      0.67      0.75        69

    accuracy                           1.00     42654
   macro avg       0.93      0.83      0.87     42654
weighted avg       1.00      1.00      1.00     42654

confusion_matrix
[[42577     8]
 [   23    46]]


SVC(random_state=1)

##  Support Vector  Machine is not a suitable algorithm for this dataset